### PR TITLE
Fixed Mesa biome generation blocks, more populators like ores, trees ,cactus, etc

### PR DESCRIPTION
**Pull request by MatthieuLepers**
- Added ores generation for overworld and nether
- Added catcus generation in desert
- Added flowers generation
- Added grass generation
- Added lakes generation (water and lava)
- Added tiny mushroom generation for overworld
- Added melon generation in jungles
- Added nether wart generation because the nether not have dungeons
- Added pumpkins generation in forests
- Added all trees generations for all biomes
- Tests success for generating a normal world with Multiverse
- Tests success for genereting a nether world with Multiverse

### CODE REVIEW

**Comment by AireAyquaza** [comment]
Mesa biomes are now correclty generated with hardened clay and red sand.

**Comment by betterphp** [comment]
Hey, thanks this looks good.

Just a couple of issues:
* The BasePlugin code should not be in this repo - it has its own repo and should only be a dependency of this project
* Can we have the commit message as something more meaningful instead of the version number? something like your comment "Mesa biomes are now correclty generated with hardened clay and red sand" would make more sense in the changelog

Thanks

**Comment by betterphp** [comment]
A build should appear on my Jenkins server once this is merged https://ci.jacekk.co.uk/job/SkylandsPlus/

**Comment by AireAyquaza** [comment]
I juste change the commit name and i've removed the baseplugin code from it, like you ask me.

**Comment by betterphp** [comment]
Sorry one more thing, can you undo the formatting changes? It looks like all of the { brackets have been moved on to a new line.

Also the changes don't need adding to the readme file - the changelog is generated from the commit messages.

If you could do that then squash the commits in to one to make it look a bit neater then I'll merge it in.

**Comment by AireAyquaza** [comment]
Just done

**Comment by betterphp** [comment]
Sorry I've been away for a few days. Looks good now.

I'll merge this in, thanks for contributing :)

**Comment by betterphp** [comment]
https://ci.jacekk.co.uk/job/SkylandsPlus/42/

Build failed because dependencies couldn't be downloaded - I'll fix that at some point :P

**Comment by MatthieuLepers** [comment]
Hi again, can you update SkylandsPlus on this page : http://dev.bukkit.org/bukkit-plugins/skylandsplus/
 ? I think minecraft community will be happy if you do that update.

**Pull request merged**
